### ISSUE TITLE
voxels near the camera are not modeled

### ISSUE THREAD

**Issue by cedrusx** [emanuelev/supereight#8]
Hi Emanuele, when I was trying with OFusion, I found that during integration only voxels near the depth points are updated, while we actually need all voxels along the ray from the camera be updated to model the free space for navigation. I think this was caused by the step setting when building the octant list. The step size near the camera seems to be too large that most blocks are skipped. So I change it from 30*voxelSize to 8*voxelSize to make sure all blocks along the ray can be processed, as shown below. Do you think it would be a proper fix for this issue? Thanks!

in compute_stepsize in bfusion/alloc_impl.hpp:
```
  if(dist_travelled < hf_band) new_step = voxelSize;
  else if(dist_travelled < hf_band + half) new_step = 10.f * voxelSize; 
  else new_step = 30.f * voxelSize;
```
-->
```
  if(dist_travelled < hf_band) new_step = voxelSize;
  else new_step = 8.f * voxelSize;
```

**Comment by emanuelev** [comment]
Hi Xuesong, thanks a lot for looking into this. The voxels representing free space between the camera and the surface should actually be modelled. The step function effectively says that we do not need full resolution for free space (at least in our use case) and so it allocates bigger voxels for it. This should be reflected when you sample the field, however in the current version trilinear interpolation is supported only on the leaves at maximum resolution and it falls back to nearest neighbour when the sample points fall into a coarser voxel. 

If you are not able to see this than something might gone miss in the massive refactoring for the opensource release. I can have a look and get back to you.

Also, your solution would be fine but effectively what you end up doing is fully allocating the whole space, sort of invalidating the point of a sparse octree structure -- meaning very bad computation performance overall.

**Comment by cedrusx** [comment]
Emanuele, thanks a lot for the quick response! Your explanation is clear and helpful to me. Now I realize the issue is that only allocated VoxelBlocks are visualized in my implementation. So I guess I should instead traverse the tree or the node buffer plus block buffer and visualize all leaf nodes/blocks (but not with the Node::isLeaf method which seems always to return true for non-block nodes). 

I am sorry for having brought another false issue. I'm trying to better understand the design and details. BTW we have already packed it into a ROS package and replaced octomap with it in our real-robot field trials. Thanks again for the great work!

**Comment by emanuelev** [comment]
Hi Xuesong, thanks a lot for your feedback, it's very valuable for us. Consider that you are using a very early alpha of the software so there are many rough edges which we are taking care of in the devel branch. It would be very useful for us if you keep us updated with your needs so that if we change something you are using we can at least discuss it in advance with you. We can take this offline to more appropriate channels (email/slack). Great also to hear that you are already actually using it on a real robot!

Regarding the problem with isLeaf, I am surprised that it's not actually working. Let me try a quick test case to see if I can reproduce the issue -- if something is broken I'm sure is going to be a very easy fix. Once that is sorted out, I would use the se::node_iterator and call isLeaf on each returned node. I'll get back to you soon.

**Comment by cedrusx** [comment]
Hi Emanuele, it's great to know that you are still actively working on this project! Yes let's talk offline. Please close this issue at your convenience.
